import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Hellci',
      email: 'hellci@example.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: true,
    },
    {
      name: 'Hellci',
      email: 'hellcitracinic@gmail.com',
      password: bcrypt.hashSync('BeautifulTango'),
      isAdmin: true,
    },
    {
      name: 'Dri',
      email: 'buskikanapika@gmail.com',
      password: bcrypt.hashSync('Buskik121'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Mesa de jantar',
      slug: 'mesa-de-jantar',
      category: 'Mesas',
      image: '/images/mesa1.jpg',
      price: 240,
      brand: 'Criare',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Mesa de jantar para seis',
    },
    {
      name: 'Mesa de cozinha',
      slug: 'mesa-de-cozinha',
      category: 'Mesas',
      image: '/images/mesa2.jpg',
      price: 120,
      brand: 'Tramontina',
      rating: 4.3,
      numReviews: 13,
      countInStock: 27,
      description: 'Mesa de cozinha de vidro',
    },
    {
      name: 'Mesa de madeira',
      slug: 'mesa-de-madeira',
      category: 'Mesas',
      image: '/images/mesa3.jpg',
      price: 240,
      brand: 'MDF Itallia',
      rating: 4.9,
      numReviews: 11,
      countInStock: 13,
      description: 'Mesa de madeira maciça',
    },
    {
      name: 'Poltrona de couro',
      slug: 'poltrona-de-couro',
      category: 'Cadeiras',
      image: '/images/cadeira1.jpg',
      price: 150,
      brand: 'Aeron',
      rating: 4.2,
      numReviews: 27,
      countInStock: 33,
      description: 'Poltrona confortável para sua sala',
    },
    {
      name: 'Cadeira de escritório',
      slug: 'cadeira-de-escritório',
      category: 'Cadeiras',
      image: '/images/cadeira2.jpg',
      price: 120,
      brand: 'Muller',
      rating: 3.2,
      numReviews: 10,
      countInStock: 55,
      description: 'Cadeira ergonômica pro seu escritório',
    },
    {
      name: 'Cadeira azul',
      slug: 'cadeira-azul',
      category: 'Cadeiras',
      image: '/images/cadeira3.jpg',
      price: 150,
      brand: 'Mymax',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Uma bela cadeira azul',
    },
  ],
};
export default data;
